"""empty message

Revision ID: 28cb172b5ab5
Revises: 075c62e475b4
Create Date: 2026-03-24 22:08:23.423601

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "28cb172b5ab5"
down_revision: Union[str, Sequence[str], None] = "075c62e475b4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "Auth", sa.Column("id", sa.Integer(), nullable=False), sa.PrimaryKeyConstraint("id")
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("Auth")
    # ### end Alembic commands ###
