"""empty message

Revision ID: 48d65e28dfb7
Revises: 70e51b596a6d
Create Date: 2026-03-25 00:06:55.537653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48d65e28dfb7'
down_revision: Union[str, Sequence[str], None] = '70e51b596a6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('A')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('A',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('aaa', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('A_pkey'))
    )
    # ### end Alembic commands ###
