"""empty message

Revision ID: 7c37d9f9f47b
Revises: 28cb172b5ab5
Create Date: 2026-03-24 22:08:41.104066

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7c37d9f9f47b"
down_revision: Union[str, Sequence[str], None] = "28cb172b5ab5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("Auth")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "Auth",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("Auth_pkey")),
    )
    # ### end Alembic commands ###
