"""empty message

Revision ID: ae1fd684ab2a
Revises: 7c37d9f9f47b
Create Date: 2026-03-24 23:04:52.523313

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ae1fd684ab2a"
down_revision: Union[str, Sequence[str], None] = "7c37d9f9f47b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "Auth", sa.Column("id", sa.Integer(), nullable=False), sa.PrimaryKeyConstraint("id")
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("Auth")
    # ### end Alembic commands ###
