"""empty message

Revision ID: ce3ea1bf0f89
Revises: ae1fd684ab2a
Create Date: 2026-03-24 23:07:58.151856

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ce3ea1bf0f89"
down_revision: Union[str, Sequence[str], None] = "ae1fd684ab2a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("Auth")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "Auth",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("Auth_pkey")),
    )
    # ### end Alembic commands ###
