import asyncio
from typing import Any

from click import Command, Context, Option
from fastapi.routing import APIRoute
from sqlalchemy import Delete, select
from sqlalchemy.dialects.postgresql import insert
from starlette.routing import Route

from src.api.rbac.models import Permission, Role, Role2Permission
from src.api.rbac.repos.role_repo import RoleRepo
from src.core.resources import resources
from src.main import app
from src.api.rbac.repos.permission_repo import PermissionRepo
from src.api.rbac.repos.role2permission_repo import Role2PermissionRepo
from src.core.constants import ROLE_CHILD_MAP, PASSED_APP_PERMISSIONS_CHECK, DEFAULT_ROLE
from src.utils.datastructures.permission_info import PermissionInfo
from src.utils.helpers import get_superior_roles


class BatchUpdatePermissionsCommand(Command):
    """No CTE, No Join, All in python code."""

    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)
        self.help = "No CTE, No Join, All in python code."
        self._dict = {"opt": {"purify": ["--purify"]}}
        self.params = [
            Option(
                param_decls=self._dict.get("opt").get("purify"),
                is_flag=True,
                default=False,
                help="Purify Role2Permission table before sync.",
            ),
        ]

    def invoke(self, ctx: Context) -> Any:
        asyncio.run(self._invoke(ctx))
        return super().invoke(ctx)

    @staticmethod
    async def _invoke(ctx: Context) -> Any:
        permissions_info: list[PermissionInfo] = []

        app_routes: list[Route | APIRoute | Any] = app.instance.routes
        for app_route in app_routes:
            # pass some fastapi built-in routes like 'openapi, swagger, redoc'
            if not isinstance(app_route, APIRoute):
                continue

            # auth app must pass
            try:
                # app name must in urlpath, e.g.: app:demo, url:/demo
                app_name = app_route.path.split("/")[1]
            except Exception as e:
                raise e

            if app_name in PASSED_APP_PERMISSIONS_CHECK:
                continue

            code = app_route.name
            metadata: dict[Any, Any] | None = app_route.openapi_extra

            if metadata is None:
                role = DEFAULT_ROLE
            else:
                role = metadata.get("role", DEFAULT_ROLE)

            role_parents_set = get_superior_roles(str(role), ROLE_CHILD_MAP)

            permissions_info.append(PermissionInfo(role=str(role), code=code, role_parents_set=role_parents_set))

        # for permission_info in permissions_info:
        #     print(f"{permission_info.code:<20} => {permission_info.role_parents_set}")

        # exit()
        await resources.init()
        async with resources.session_factory() as db:  # manually manage db context
            try:
                # get the repos
                perm_repo: Any = PermissionRepo(db)
                role_repo: Any = RoleRepo(db)
                role2perm_repo = Role2PermissionRepo(db)

                # get perms: [{'code': 'login'}, {'code': 'register'}, ...]
                valid_perms = [perm_info.code for perm_info in permissions_info]
                permissions_params = [{"code": code} for code in valid_perms]

                # batch update perms

                stat = (
                    insert(Permission)
                    .on_conflict_do_nothing(index_elements=["code"])
                    .returning(Permission.code, Permission.id)
                )
                perm_code_id_list = await perm_repo.execute_stat_params(stat, permissions_params)

                if perm_code_id_list is None:
                    # no update
                    await db.close()
                    return

                # get all valid perm-code-id-map
                stat = select(Permission.code, Permission.id)
                perm_code_id_list = await perm_repo.execute_stat_params(stat)
                perm_code_id_map = {perm.code: perm.id for perm in perm_code_id_list}
                # print(perm_code_id_map)

                # del dirty data(necessary, because 1-perm <-> 1-url-method, perms are generated by code dynamically)
                stat = Delete(Permission).where(~Permission.code.in_(valid_perms))
                await perm_repo.execute_stat_params(stat)

                # get roles
                role_names_set: set[str] = get_superior_roles(str(DEFAULT_ROLE), ROLE_CHILD_MAP)
                # get role-name-id-map
                stat = select(Role.name, Role.id).where(Role.name.in_(role_names_set))
                roles = await role_repo.execute_stat_params(stat)
                role_name_id_map = {role.name: role.id for role in roles}
                # print(role_name_id_map)

                # update role2perm
                # insert into role2perm params
                role2perm_params = []
                for permission_info in permissions_info:
                    perm_id = perm_code_id_map.get(permission_info.code)
                    for role_name in permission_info.role_parents_set:
                        role_id = role_name_id_map.get(role_name)
                        if role_id and perm_id:
                            role2perm_params.append({"role_id": role_id, "permission_id": perm_id})
                # print(role2perm_params)
                # clean up role2perm
                # configuration as code, please do not use admin-site to do role-perm operations.

                purify = ctx.params.get("purify")
                if purify:
                    stat = Delete(Role2Permission)
                    await role2perm_repo.execute_stat_params(stat)

                if role2perm_params:
                    stat = insert(Role2Permission).on_conflict_do_nothing(index_elements=["role_id", "permission_id"])
                    await role2perm_repo.execute_stat_params(stat, role2perm_params)

                await db.commit()
                # this is what I do the same thing in Django orm.
                # In Django, it's pretty simple, but speed is low.
                # in Sqlalchemy Core, it is fast, but much harder.
                # for permission in permissions:
                #     code = permission.code
                #     url = permission.url
                #     role_names = permission.role_parents_set
                #
                #     perm, _ = Permission.objects.update_or_create(
                #         code=code,
                #         url=url
                #     )
                #
                #     for role_name in role_names:
                #         role = Role.objects.get(name=role_name)
                #         Role2Permission.objects.update_or_create(
                #             role_id=role.id,
                #             permission_id=perm.id
                #         )
            except Exception as e:
                await db.rollback()
                raise e
