"""empty message

Revision ID: 4827a1cb7efe
Revises: dbbf7d6b41b9
Create Date: 2026-03-31 22:06:11.796005

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "4827a1cb7efe"
down_revision: Union[str, Sequence[str], None] = "dbbf7d6b41b9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "Department",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("Rbac_User", sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False))
    op.add_column("Rbac_User", sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False))
    op.drop_column("Rbac_User", "created_time")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "Rbac_User",
        sa.Column(
            "created_time", postgresql.TIMESTAMP(), server_default=sa.text("now()"), autoincrement=False, nullable=False
        ),
    )
    op.drop_column("Rbac_User", "updated_at")
    op.drop_column("Rbac_User", "created_at")
    op.drop_table("Department")
    # ### end Alembic commands ###
