"""empty message

Revision ID: 4d5a074e4258
Revises:
Create Date: 2026-04-09 16:44:57.867906

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4d5a074e4258"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "Rbac_Permission",
        sa.Column("code", sa.String(length=256), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    op.create_table(
        "Rbac_Role",
        sa.Column("name", sa.String(length=16), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "Rbac_Role2Permission",
        sa.Column("role_id", sa.Integer(), nullable=False),
        sa.Column("permission_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("role_id", "permission_id", name="unique_role_permission"),
    )
    op.create_index(
        op.f("ix_Rbac_Role2Permission_permission_id"), "Rbac_Role2Permission", ["permission_id"], unique=False
    )
    op.create_index(op.f("ix_Rbac_Role2Permission_role_id"), "Rbac_Role2Permission", ["role_id"], unique=False)
    op.create_table(
        "Rbac_User",
        sa.Column("name", sa.String(length=16), nullable=False),
        sa.Column("email", sa.String(length=32), nullable=False),
        sa.Column("password", sa.String(length=256), nullable=False),
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "Rbac_User2Role",
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("role_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "role_id", name="unique_user_role"),
    )
    op.create_index(op.f("ix_Rbac_User2Role_role_id"), "Rbac_User2Role", ["role_id"], unique=False)
    op.create_index(op.f("ix_Rbac_User2Role_user_id"), "Rbac_User2Role", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_Rbac_User2Role_user_id"), table_name="Rbac_User2Role")
    op.drop_index(op.f("ix_Rbac_User2Role_role_id"), table_name="Rbac_User2Role")
    op.drop_table("Rbac_User2Role")
    op.drop_table("Rbac_User")
    op.drop_index(op.f("ix_Rbac_Role2Permission_role_id"), table_name="Rbac_Role2Permission")
    op.drop_index(op.f("ix_Rbac_Role2Permission_permission_id"), table_name="Rbac_Role2Permission")
    op.drop_table("Rbac_Role2Permission")
    op.drop_table("Rbac_Role")
    op.drop_table("Rbac_Permission")
    # ### end Alembic commands ###
