"""empty message

Revision ID: e830185f3ef6
Revises: 4d5a074e4258
Create Date: 2026-04-17 15:45:37.174593

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e830185f3ef6"
down_revision: Union[str, Sequence[str], None] = "4d5a074e4258"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "UserProfile",
        sa.Column("id", sa.BigInteger(), autoincrement=False, nullable=False, comment="same as Rbac_User.id"),
        sa.Column("avatar", sa.String(length=256), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_constraint(op.f("Rbac_User_email_key"), "Rbac_User", type_="unique")
    op.create_index(
        "unique_user_email_active", "Rbac_User", ["email"], unique=True, postgresql_where=sa.text("is_deleted IS FALSE")
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("unique_user_email_active", table_name="Rbac_User", postgresql_where=sa.text("is_deleted IS FALSE"))
    op.create_unique_constraint(
        op.f("Rbac_User_email_key"), "Rbac_User", ["email"], postgresql_nulls_not_distinct=False
    )
    op.drop_table("UserProfile")
    # ### end Alembic commands ###
