"""empty message

Revision ID: f6de1f134829
Revises: 4827a1cb7efe
Create Date: 2026-04-01 13:54:06.982778

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f6de1f134829"
down_revision: Union[str, Sequence[str], None] = "4827a1cb7efe"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("Rbac_User", "id", existing_type=sa.INTEGER(), type_=sa.BigInteger(), existing_nullable=False)
    op.alter_column(
        "Rbac_User2Role", "user_id", existing_type=sa.INTEGER(), type_=sa.BigInteger(), existing_nullable=False
    )
    op.alter_column("Rbac_User2Role", "id", existing_type=sa.INTEGER(), type_=sa.BigInteger(), existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("Rbac_User2Role", "id", existing_type=sa.BigInteger(), type_=sa.INTEGER(), existing_nullable=False)
    op.alter_column(
        "Rbac_User2Role", "user_id", existing_type=sa.BigInteger(), type_=sa.INTEGER(), existing_nullable=False
    )
    op.alter_column("Rbac_User", "id", existing_type=sa.BigInteger(), type_=sa.INTEGER(), existing_nullable=False)
    # ### end Alembic commands ###
