"""empty message

Revision ID: 21231be54cf8
Revises: 6c2450dc53a0
Create Date: 2026-03-19 14:57:46.497660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21231be54cf8'
down_revision: Union[str, Sequence[str], None] = '6c2450dc53a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'Rbac_Permission', ['code'])
    op.create_unique_constraint(None, 'Rbac_User', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Rbac_User', type_='unique')
    op.drop_constraint(None, 'Rbac_Permission', type_='unique')
    # ### end Alembic commands ###
