"""empty message

Revision ID: 37a2133546f9
Revises: 21231be54cf8
Create Date: 2026-03-19 15:00:31.177903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37a2133546f9'
down_revision: Union[str, Sequence[str], None] = '21231be54cf8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'Rbac_Role', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Rbac_Role', type_='unique')
    # ### end Alembic commands ###
