"""update

Revision ID: 6c2450dc53a0
Revises: 7f5f45764483
Create Date: 2026-03-16 22:31:27.185758

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6c2450dc53a0"
down_revision: Union[str, Sequence[str], None] = "7f5f45764483"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("Rbac_Permission", "url")
    op.add_column("Rbac_User", sa.Column("email", sa.String(length=32), nullable=False))
    op.add_column("Rbac_User", sa.Column("password", sa.String(length=256), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("Rbac_User", "password")
    op.drop_column("Rbac_User", "email")
    op.add_column(
        "Rbac_Permission",
        sa.Column("url", sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    )
    # ### end Alembic commands ###
