"""migrate_to_rbac_structure

Revision ID: 7b4190e57466
Revises:
Create Date: 2026-03-13 00:24:03.235664

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "7b4190e57466"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### default_commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "Rbac_Permission",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=256), nullable=False),
        sa.Column("url", sa.String(length=256), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "Rbac_Role",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=16), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "Rbac_Role2Permission",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("role_id", sa.Integer(), nullable=False),
        sa.Column("permission_id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("role_id", "permission_id", name="unique_role_permission"),
    )
    op.create_index(
        op.f("ix_Rbac_Role2Permission_permission_id"),
        "Rbac_Role2Permission",
        ["permission_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_Rbac_Role2Permission_role_id"), "Rbac_Role2Permission", ["role_id"], unique=False
    )
    op.create_table(
        "Rbac_User",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=16), nullable=False),
        sa.Column("created_time", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "Rbac_User2Role",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("role_id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "role_id", name="unique_user_role"),
    )
    op.create_index(op.f("ix_Rbac_User2Role_role_id"), "Rbac_User2Role", ["role_id"], unique=False)
    op.create_index(op.f("ix_Rbac_User2Role_user_id"), "Rbac_User2Role", ["user_id"], unique=False)
    op.drop_table("User")
    # ### end Alembic default_commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### default_commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "User",
        sa.Column("name", sa.VARCHAR(length=50), autoincrement=False, nullable=True),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "created_time",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("is_deleted", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("User_pkey")),
    )
    op.drop_index(op.f("ix_Rbac_User2Role_user_id"), table_name="Rbac_User2Role")
    op.drop_index(op.f("ix_Rbac_User2Role_role_id"), table_name="Rbac_User2Role")
    op.drop_table("Rbac_User2Role")
    op.drop_table("Rbac_User")
    op.drop_index(op.f("ix_Rbac_Role2Permission_role_id"), table_name="Rbac_Role2Permission")
    op.drop_index(op.f("ix_Rbac_Role2Permission_permission_id"), table_name="Rbac_Role2Permission")
    op.drop_table("Rbac_Role2Permission")
    op.drop_table("Rbac_Role")
    op.drop_table("Rbac_Permission")
    # ### end Alembic default_commands ###
