services:
  #  web:  # when each branch's tests pass, enable this service
  #    build: .
  #    ports:
  #      - "8000:5000"
  #    develop:
  #      watch:
  #        - action: sync
  #          path: .
  #          target: /code
  redis:
    image: redis:7.2-alpine
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redisdata:/data
    command:
      - redis-server
      - --bind
      - 0.0.0.0
      - --protected-mode
      - "no"
      - --appendonly
      - "yes"
      - --requirepass
      - "${REDIS_PASSWORD}"

  postgres:
    image: postgres:16.2
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PW}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
  redisdata:
