name: fastapi_template_services
services:
  #  web:  # when each branch's tests pass, enable this service
  #    build: .
  #    ports:
  #      - "8000:5000"
  #    develop:
  #      watch:
  #        - action: sync
  #          path: .
  #          target: /code
  cache:
    container_name: cache_fastapi_template
    image: redis:7.2-alpine
    ports:
      - "${CACHE_REDIS_PORT}:6379"
    volumes:
      - ./data/redis/cache:/data
    command:
      - redis-server
      - --bind
      - "${CACHE_REDIS_HOST}"
      - --protected-mode
      - "no"
      - --appendonly
      - "yes"
      - --requirepass
      - "${CACHE_REDIS_PASSWORD}"
  broker:
    container_name: broker_fastapi_template
    image: redis:7.2-alpine
    ports:
      - "${BROKER_REDIS_PORT}:6379"
    volumes:
      - ./data/redis/broker:/data
    command:
      - redis-server
      - --bind
      - "${BROKER_REDIS_HOST}"
      - --protected-mode
      - "no"
      - --appendonly
      - "yes"
      - --requirepass
      - "${BROKER_REDIS_PASSWORD}"
  postgres:
    container_name: postgresql_fastapi_template
    image: postgres:16.2
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PW}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

