name: fastapi_template_services
services:
  #  web:  # when each branch's tests pass, enable this service
  #    build: .
  #    ports:
  #      - "8000:5000"
  #    develop:
  #      watch:
  #        - action: sync
  #          path: .
  #          target: /code
  cache:
    container_name: cache_fastapi_template
    image: redis:7.2-alpine
    ports:
      - "${CACHE_REDIS_PORT}:6379"
    volumes:
      - ./data/redis/cache:/data
    command:
      - redis-server
      - --bind
      - "${CACHE_REDIS_HOST}"
      - --protected-mode
      - "no"
      - --appendonly
      - "yes"
      - --requirepass
      - "${CACHE_REDIS_PASSWORD}"
  broker:
    container_name: broker_fastapi_template
    image: redis:7.2-alpine
    ports:
      - "${BROKER_REDIS_PORT}:6379"
    volumes:
      - ./data/redis/broker:/data
    command:
      - redis-server
      - --bind
      - "${BROKER_REDIS_HOST}"
      - --protected-mode
      - "no"
      - --appendonly
      - "yes"
      - --requirepass
      - "${BROKER_REDIS_PASSWORD}"
  postgres:
    container_name: postgresql_fastapi_template
    image: postgres:16.2
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PW}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
  s3_minio:
    container_name: s3_minio_fastapi_template
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    ports:
      - "${S3_SERVER_PORT}:9000"
      - "${S3_CONSOLE_PORT}:9001"
    environment:
      MINIO_ROOT_USER: ${S3_ACCESS_KEY_ID}
      MINIO_ROOT_PASSWORD: ${S3_ACCESS_KEY_SECRET}
    volumes:
      - ./data/s3/minio:/data
  doc_db:
    image: mongo:7
    container_name: doc_db_fastapi_template
    ports:
      - "${DOC_DB_PORT}:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DOC_DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DOC_DB_PASSWORD}
    volumes:
      - ./data/mongodb:/data/db
  log_db:
    image: apache/kafka:4.2.0
    container_name: log_db_fastapi_template
    hostname: kafka
    ports:
      - "${LOG_DB_PORT}:9092"
    environment:
      # kraft
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      # listeners
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      # protocol map
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      # controller quorum
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      # single node
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      # logs
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
    volumes:
      - ./data/kafka:/var/lib/kafka/data
  mq:
    image: rabbitmq:4.2-management
    container_name: mq_fastapi_template
    hostname: rabbitmq
    ports:
      - "${RABBITMQ_SERVER_PORT}:5672"
      - "${RABBITMQ_WEB_UI_PORT}:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
      RABBITMQ_DEFAULT_VHOST: /
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "check_port_connectivity" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./data/rabbitmq:/var/lib/rabbitmq