"""empty message

Revision ID: 270659907a20
Revises:
Create Date: 2026-05-14 17:19:33.382609

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "270659907a20"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "Region",
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(length=32), nullable=False),
        sa.Column("type", sa.String(length=16), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_Region_parent_id"), "Region", ["parent_id"], unique=False)
    op.create_table(
        "UserAddress",
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("country_id", sa.Integer(), nullable=False),
        sa.Column("region_id", sa.Integer(), nullable=False),
        sa.Column("detail_address", sa.String(length=64), nullable=False),
        sa.Column("postal_code", sa.String(length=16), nullable=False),
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_UserAddress_country_id"), "UserAddress", ["country_id"], unique=False)
    op.create_index(op.f("ix_UserAddress_region_id"), "UserAddress", ["region_id"], unique=False)
    op.create_index(op.f("ix_UserAddress_user_id"), "UserAddress", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_UserAddress_user_id"), table_name="UserAddress")
    op.drop_index(op.f("ix_UserAddress_region_id"), table_name="UserAddress")
    op.drop_index(op.f("ix_UserAddress_country_id"), table_name="UserAddress")
    op.drop_table("UserAddress")
    op.drop_index(op.f("ix_Region_parent_id"), table_name="Region")
    op.drop_table("Region")
    # ### end Alembic commands ###
