"""empty message

Revision ID: 5001e4246519
Revises: 
Create Date: 2026-05-14 17:49:30.489213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5001e4246519'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Region_parent_id'), table_name='Region')
    op.drop_table('Region')
    op.drop_index(op.f('ix_UserAddress_country_id'), table_name='UserAddress')
    op.drop_index(op.f('ix_UserAddress_region_id'), table_name='UserAddress')
    op.drop_index(op.f('ix_UserAddress_user_id'), table_name='UserAddress')
    op.drop_table('UserAddress')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('UserAddress',
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('country_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('region_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('detail_address', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('postal_code', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('UserAddress_pkey'))
    )
    op.create_index(op.f('ix_UserAddress_user_id'), 'UserAddress', ['user_id'], unique=False)
    op.create_index(op.f('ix_UserAddress_region_id'), 'UserAddress', ['region_id'], unique=False)
    op.create_index(op.f('ix_UserAddress_country_id'), 'UserAddress', ['country_id'], unique=False)
    op.create_table('Region',
    sa.Column('parent_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('Region_pkey'))
    )
    op.create_index(op.f('ix_Region_parent_id'), 'Region', ['parent_id'], unique=False)
    # ### end Alembic commands ###
