name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Poetry
        run: pip install poetry

      - name: Install dependencies
        run: poetry install --no-interaction --no-root

      - name: pre-commit
        run: poetry run pre-commit run -a

      # gitHub action runner real path is in  root, so use ./env, ./docker, not ../../env,...
      - name: Start Postgres for Testing
        run: |
          sed -i 's/192.168.8.7/localhost/g' ./envs/.env.docker.test
          docker compose \
            --env-file ./envs/.env.docker.test \
            -f ./docker/compose.test.yaml \
            up -d \
            --remove-orphans
          echo "Waiting for Postgres to be ready..."
          until docker exec test_postgresql_fastapi_template pg_isready -U jack; do
            sleep 2
          done
      - name: Run tests with coverage
        env:
          # define an env var, only valid in ci check.
          # because in tests/conftest.py, ci cannot read private ip like 192.168.x.x
          # so define a local loop ip, let gitHub runner can run tests.
          # but we need use os.getenv() in conftest.py
          TEST_DATABASE_URL: postgresql+psycopg2://jack:jack021213@localhost:5433/test_fastapi_template
        run: |
          poetry run coverage run -m pytest -v